title: Ninho da Andorinha
description: Alimentando novas ninhadas de desenvolvedores.

theme: jekyll-theme-cayman
show_downloads: false
lang: pt-BR

gems:
  - jekyll-sitemap

exclude:
  - LICENSE.md
  - README.md
  - CNAME
